### ISSUE TITLE
Help not sure how to fix the this issue.

### ISSUE THREAD

**Issue by Scoston** [keithjjones/hostintel#1]
Great tool by the way!
Traceback (most recent call last):
  File "hostintel.py", line 80, in <module>
    geoip2citydb = ConfigFile.get('GeoIP2','City_Path')
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'GeoIP2'

**Comment by keithjjones** [comment]
Thanks!  I assume you fixed it?
