### ISSUE TITLE
Not sure how to fix this

### ISSUE THREAD

**Issue by Scoston** [keithjjones/hostintel#2]
Traceback (most recent call last):
  File "hostintel.py", line 193, in <module>
    OTX.add_row(host,row)
  File "/home/sansforensics/hostintel/libs/otx.py", line 72, in add_row
    otxgendata = self.otx.get(self.domainurl.format(host,'general'))
  File "/usr/local/lib/python2.7/dist-packages/OTXv2.py", line 83, in get
    json_data = json.loads(data)
  File "/usr/lib/python2.7/json/**init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by keithjjones** [comment]
That's an issue with the OTXv2 module I use.  It must not deal with getting a non answer.  Best I can do is put a try/except block around it.  Is it reproducible?  Are you able to tell me what input caused it @scoston?

**Comment by Scoston** [comment]
http://www.mspaintadventures.com this is what caused the error. 
File "hostintel.py", line 193, in <module>
    OTX.add_row(host,row)
  File "/home/sansforensics/hostintel/libs/otx.py", line 72, in add_row
    otxgendata = self.otx.get(self.domainurl.format(host,'general'))
  File "/usr/local/lib/python2.7/dist-packages/OTXv2.py", line 83, in get
    json_data = json.loads(data)
  File "/usr/lib/python2.7/json/**init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by keithjjones** [comment]
Ahh, that's the issue.  I wrote it to only lookup IPv4, hostnames, and domains.  I don't have protocol (http://) built into it (yet).  I'll close this issue now.  If I misunderstood you or you needed something else, go ahead and reopen it.

Thanks for using this tool @Scoston!
