### ISSUE TITLE
OTXv2- 'NoneType' object has no attribute 'read'

### ISSUE THREAD

**Issue by ryanshuck** [keithjjones/hostintel#5]
ERROR:  An exception was raised!  Raising original exception for debugging.
Traceback (most recent call last):
  File "/Users/rshuck/Desktop/hostintel/hostintel.py", line 193, in <module>
    OTX.add_row(host,row)
  File "/Users/rshuck/Desktop/hostintel/libs/otx.py", line 59, in add_row
    otxrepdata = self.otx.get(self.ipv4url.format(host,'reputation')).get('reputation',{})
  File "/Library/Python/2.7/site-packages/OTXv2.py", line 82, in get
    data = response.read().decode('utf-8')
AttributeError: 'NoneType' object has no attribute 'read'

**Comment by keithjjones** [comment]
Test that.  If it helps, I'll merge into master.  Just give me the word.

**Comment by keithjjones** [comment]
I merged into master.
