### ISSUE TITLE
OTX Error Message

### ISSUE THREAD

**Issue by keyboardcowboy1515** [keithjjones/hostintel#7]
Keith,

First, I must commend you on an AMAZING resource.  Thank you for developing a valuable Python project that has already increased my coding learning curve!

### ORIGINAL CMD ###
root@kali:~/Documents/hostintel# python hostintel.py myconfigfile.conf myhosts.txt -o > 26FEB-HostIntel-OTX.csv

### ERROR MESSAGE ###

*** Processing 98.126.67.114, ***
ERROR:  An exception was raised!  Raising original exception for debugging.
Traceback (most recent call last):
  File "hostintel.py", line 193, in <module>
    OTX.add_row(host,row)
  File "/root/Documents/hostintel/libs/otx.py", line 61, in add_row
    otxgendata = self.otx.get(self.ipv4url.format(host, 'general'))
  File "/usr/local/lib/python2.7/dist-packages/OTXv2.py", line 83, in get
    json_data = json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

# Regards!

**Comment by keyboardcowboy1515** [comment]
KEITH,

I have fixed the error.

My INPUTFILE was comma separated; however, after removing the commas the error was resolved.

Such a pleasure to have your tool.

KEYBOARDCOWBOY1515

**Comment by keithjjones** [comment]
Awesome, thank you for your kind words.
